### ISSUE TITLE
Error while installing vircpt

### ISSUE THREAD

**Issue by asitemade4u** [abbbi/vircpt#2]
**Version used**
Latest, as I `git clone https://github.com/abbbi/vircpt.git`

**Describe the bug**
- I did, as `root`:
```bash
cd vircpt/
python3 setup.py install
```
- Then when I execute `vircpt`from the Terminal, I get an error and the script won't execute (see error message below).

**Expected behavior**
After installing vircpt according to the rules, the script should work.

**Logfiles:**
```log
Traceback (most recent call last):
  File "/usr/local/bin/vircpt", line 4, in <module>
    __import__('pkg_resources').run_script('vircpt==0.1', 'vircpt')
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 651, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/lib/python3.9/site-packages/pkg_resources/__init__.py", line 1436, in run_script
    raise ResolutionError(
pkg_resources.ResolutionError: Script 'scripts/vircpt' not found in metadata at '/usr/local/lib/python3.9/site-packages/vircpt-0.1.dist-info'
```

**Workaround:**
None.

**Comment by abbbi** [comment]
Phython3 links to which version?

**Comment by asitemade4u** [comment]
```bash
python3 --version
Python 3.9.19
```

**Comment by abbbi** [comment]
Install path? Error message refers to /usr/local, I don’t think alma installs Python wheels there. Looks like a python env issue, consider using a venv
